### ISSUE TITLE
Roadmap to stable v1.0.0

### ISSUE THREAD

**Issue by clue** [reactphp/event-loop#101]
Let's face it, this project is *stable* and has been used in production for years :shipit: 

However, we're currently following a v0.X.Y release scheme (http://sentimentalversioning.org/).

We should finally make this explicit and fully adhere to SemVer and release a stable v1.0.0.

To a large extend, a stable v1.0.0 helps making BC breaks more explicit and thus the whole project more reliable from a consumer perspective. This project is actively maintained and has received some major updates in the last weeks and has some major updates planned in the next weeks. Given our current versioning scheme, we'd like to ensure all anticipated BC breaks will be merged before the planned v1.0.0 release.

As such, I've set up a roadmap that enlists only the major changes for each version among with planned release dates towards a stable v1.0.0 release:

## v0.4.3 :white_check_mark: 

* Released 2017-04-27
* Bugfix release

## v0.5.0 :white_check_mark: 

* Released 2018-04-05
* Signal handling support
* Documentation overhaul
* Reduce public API
* Throw on error

## v1.0.0

* Planned 2018-Q2?
* No new changes planned, this should merely mark the previous release as "stable"

This ticket aims to serve as a basic overview and does not contain every single change. Please also see the milestone links and the CHANGELOG for more details.

Obviously, this roadmap is subject to change and I'll try to keep it updated as we progress. In order to avoid cluttering this, please keep discussion in this ticket to a minimum and consider reaching out to us through new tickets or Twitter etc.

**Comment by WyriHaximus** [comment]
Updated as [`v0.4.3`](https://github.com/reactphp/event-loop/releases/tag/v0.4.3) has just been released

**Comment by kelunik** [comment]
What's the status of 0.5.0?

**Comment by WyriHaximus** [comment]
@kelunik We're focussing on `react/http:v0.8.0` first and then focus on `0.5.0`, there are some outstanding issues to be resolved before it's ready: https://github.com/reactphp/event-loop/milestone/2

**Comment by rrajkomar** [comment]
@WyriHaximus : The provided link does not contain any issue at the moment.
Is there something else holding the 0.5.0 version back ?
I could really use the latest fixes related to signal handling committed on July 2017 but the last tagged version (0.4.3) was released on April 2017 (see https://github.com/reactphp/event-loop/issues/101#issuecomment-297683235).
If the 0.5.0 version cannot be released yet, could we have a 0.4.4 version asap ?

**Comment by WyriHaximus** [comment]
@rrajkomar All currently open issues for `0.5.0` have been closed https://github.com/reactphp/event-loop/milestone/2?closed=1 but AFAIK @clue has a PR or two he wants to file cleaning some things up before tagging `0.5.0`

**Comment by clue** [comment]
Updated now that the v0.5.0 release is out :shipit:

Unless we find any major blockers, there's hope that this is the last noteworthy release before we get to tag this as v1.0.0 :tada:

**Comment by clue** [comment]
The very first stable v1.0.0 release with LTS has just been tagged and released! :tada:
