### ISSUE TITLE
Why callbacks cannot throw exceptions?

### ISSUE THREAD

**Issue by marcospassos** [reactphp/event-loop#108]
I'd like to use the event loop to limit the max execution time of a given function, instead of the native `set_time_limit`. However, the documentation says the callback function should not throw exceptions.

Is there any other way to do this?

```php
$loop->addTimer(0.1, function () {
    throw new TimeoutException('Max execution of 100ms');
});
```

**Comment by kelunik** [comment]
There's no way to achieve what you want with ReactPHP. As long as your function blocks, ReactPHP won't be able to execute your timer and abort anything.

**Comment by clue** [comment]
Thanks for opening this ticket :+1: 

The loop allows you to execute multiple async operations in parallel, as such it's more likely you'll want to attach a timeout to individual promises. Have you seen https://github.com/reactphp/promise-timer#timeout yet?

As an alternative, it's not really recommended to interfere with the loop in this way, but what you're trying can also be achieved by stopping the loop and then throwing.

I hope this helps :+1:

**Comment by marcospassos** [comment]
Thank you, @clue!
