### ISSUE TITLE
100% CPU with ExtEventLoop

### ISSUE THREAD

**Issue by kelunik** [reactphp/event-loop#109]
See https://gist.github.com/kelunik/79f843c541aceb3927c5463cc643d502 for a reproduction script.

While the child process runs, `php test.php` consumes 100% CPU when running on the `ExtEventLoop`. Additionally, the connection is closed directly instead of one second later if there's currently a child process running.

See also https://twitter.com/kelunik/status/917757971790286848 and replies.

**Comment by clue** [comment]
Thank you for filing this issue! I think it serves as a valid reference that suggests https://github.com/reactphp/child-process/issues/51 may actually be an issue for some use cases.

Given that it's related to this known issue in another component, I don't see much that we could do here in this component.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by kelunik** [comment]
@clue It works fine with the `StreamSelectLoop`. While it might be related to the linked issue, it probably shouldn't result in 100% CPU usage. The only expected issue with https://github.com/reactphp/child-process/issues/51 is connections being kept open, but `stream_socket_shutdown` seems to solve that. Without `stream_socket_shutdown`, I get the expected hanging behavior with the `StreamSelectLoop`. I believe this is a separate issue.

**Comment by clue** [comment]
Can you send in a gist to reproduce this issue without the known issue linked above? Thank you.

**Comment by kelunik** [comment]
Please re-open the issue, so I don't forget about it.

**Comment by clue** [comment]
No worries, I'll make sure to ping you if nothing changes about this issue in a few days and will reopen if you send a gist to reproduce this! :+1: Thank you.

**Comment by clue** [comment]
Ping @kelunik, I suppose this is still resolved? :+1:

**Comment by kelunik** [comment]
It's weird. If I try to look into it with `phpdbg` and pause the execution and continue it again, the 100% CPU usage is gone. Seems to be a Heisenbug. Haven't found another reproduction case, because I'm not sure what causes it. So no, it's not resolved as stated previously. It's not the expected behavior that https://github.com/reactphp/child-process/issues/51 might case, as previously stated.

**Comment by clue** [comment]
@kelunik Thanks for trying to dig into this. If you happen to find a way to reproduce this, I'm happy to re-open this so we can look into this :+1:

**Comment by lajosbencz** [comment]
I've ran into this issue aswell, i'm installing ```react/child-process:0.6.1``` from composer, and the default event loop (React\EventLoop\ExtUvLoop) consumes 100% of the CPU.
If i explicitly set it to StreamSelectLoop, the process works as expected at around 5-10% CPU usage.

The project im using it in: https://github.com/lajosbencz/phrocman

Could it be purely related to the loop implementation, and nothing to do with the component itself?

**Comment by clue** [comment]
@lajosbencz We're not aware of any such issues at the moment. Can you provide a minimal test script to reproduce this locally?

If this is related to spawning child-processes, can you take a look at one of the possible work-arounds for https://github.com/reactphp/child-process/issues/51, such as https://github.com/clue/reactphp-sqlite/pull/7?
