### ISSUE TITLE
Remove misleading Composer suggest keywords

### ISSUE THREAD

**Issue by clue** [reactphp/event-loop#114]
For example, if I have `ext-ev` installed, Composer still suggest installing `ext-libevent` while it's unclear from a consumer's perspective how much value this provides.

Note that #113 has improved the suggest keyword description for each extension somewhat, but I believe this is more an issue with how Composer suggests these dependencies and now really something that can be addressed in this package.

As an alternative, I suggest simply dropping the `suggest` keyword completely. Is much gained by having this in place? Instead, I would suggest updating our install instructions to detail why having *either* extension can be a good thing (under what circumstances anyway?).

**Comment by WyriHaximus** [comment]
I'm ensure about this tbh. Totally agree on the #116 side of things but unsure about removing it totally as it does give extra exposure to the available event loops.
