### ISSUE TITLE
Documentation for recommended EventLoop implementation and requirements

### ISSUE THREAD

**Issue by clue** [reactphp/event-loop#116]
Why should consumers care about the EventLoop implementation and how can each extension be installed? We should merge https://github.com/reactphp/react/wiki/Event-Loop-Implementations into the documentation and then remove this wiki page.

**Comment by WyriHaximus** [comment]
Sure I'll pick that up, makes perfect sense 👍

**Comment by clue** [comment]
@WyriHaximus Thank you! By the way, I think using free text with according sections also makes much more sense than keeping this tabular layout :+1:

**Comment by WyriHaximus** [comment]
@clue it does, but that also means I have to dive in the differences between each loop to create a nice small bit of text for each loop.

**Comment by WyriHaximus** [comment]
@clue was just diving into this and came across https://github.com/reactphp/event-loop#loop-implementations anything you want to see added there specifically?

**Comment by clue** [comment]
@WyriHaximus Perhaps some installation instructions and/or recommendations? Like, why would users even care about having multiple extensions available? Also, I suppose it makes sense to explicitly say that extensions are not *required*, but highlight *why* installing *which* extension makes sense for common use cases?

**Comment by WyriHaximus** [comment]
@clue SGTM 👍 

> but highlight *why* installing *which* extension makes sense for common use cases?

Is going to be fun 🎉
