### ISSUE TITLE
How to read response from smtp server?

### ISSUE THREAD

**Issue by sevikerr** [reactphp/event-loop#117]
I connecting to SMTP server. (`alt1.gmail-smtp-in.l.google.com:25` for example)
How can i read response when i write `$connection->write('HELO alt1.gmail-smtp-in.l.google.com');`?

**Comment by clue** [comment]
Thanks for posting the question. It looks like this is more related to the socket component?

Have you checked the [`data` event](https://reactphp.org/stream/#data-event) and the examples, such as [this one](https://github.com/reactphp/socket/blob/master/examples/11-http.php#L15)?

I hope this helps :+1:
