### ISSUE TITLE
Multiple event loop

### ISSUE THREAD

**Issue by sm2017** [reactphp/event-loop#122]
How can I have multiple event loop in a script??Without blocking each other . I want to use `select` and `event`

**Comment by kelunik** [comment]
You can't, unless one calls the other in a busy waiting manner. Why do you want two?

**Comment by sm2017** [comment]
The reason is https://github.com/reactphp/event-loop/issues/121

I want have `event` as main loop and `select` for pg_socket

**Comment by WyriHaximus** [comment]
@sm2017 you can't without the loops blocking each other, have you tried any of the [other](https://github.com/reactphp/event-loop#loop-implementations) event loops?

**Comment by mbonneau** [comment]
@sm2017 - If you are just looking for an async way to use Postgres - take a look at https://github.com/voryx/PgAsync which is based on react and rxphp.

This library is a 100% native PHP implementation.

**Comment by clue** [comment]
The short version is: You can't.

The longer version is: You shouldn't. There are a number of work-arounds which basically resolve to polling one loop from the other one as @kelunik suggested or you may spawn/fork multiple processes  and use some kind of IPC protocol etc.

The linked ticket #121 is a very specific issue with `ext-event`, so I would still suggest reporting this upstream and validating why this causes a `SEGFAULT` to begin with. As an alternative, I would suggest looking into using one of the alternative loop implementations as @WyriHaximus suggested. Also, @mbonneau made a very good point about using another database layer to avoid this issue in the first place.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
