### ISSUE TITLE
how can I get out of the loop (futuretick)

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/event-loop#134]
Hi how can I get out of the loop (futuretick) correctly with a command, key or typing in the console

example code

```
function fooBar($loop) {
    return function () use ($loop) {
       // my code 

// end my code
sleep(1);
        $loop->futureTick(fooBar($loop));
    };
}

$loop->futureTick(fooBar($loop));
$loop->run();
```

As I exit this loop correctly and without a Ctrl + C program I interrupt the running program

**Comment by kelunik** [comment]
You can either register a readability watcher on `STDIN` / use a stream and exit the loop in case on specific data or register a signal watcher. For signals you can use https://github.com/mkraemer/react-pcntl or use the current `master` branch which already contains signal support for the next release.

**Comment by Juanperezc** [comment]
Hi, I'm watching and PCNTL does not support windows :(

**Comment by kelunik** [comment]
Windows sucks. :-( Process pipes are file handles and do not allow non-blocking access on Windows, I think the same is true from within the process, but I'm not entirely sure. @clue might be able to shed some light there.

**Comment by clue** [comment]
Thanks for reaching out @Juanperezc. I'm not sure I follow the exact problem you're having here, maybe you can rephrase the question or provide a short gist to reproduce this locally?

I'm not sure what your code is supposed to do, but it looks like you're trying to use blocking function calls here? This is against the very core idea of ReactPHP, so you may have to rewrite things a bit to take advantage of the loop.

**Comment by Juanperezc** [comment]
Hi @clue what I want to do is something simple. Leaving the loop safely, I mean without pressing the control key + c but with a command or other form that allows me to get out of the cycle and not interrupt the program abruptly

This is an example of code that I did to show more or less what I want to do

`use React\EventLoop\Factory as EventLoop;

$loop = EventLoop::create();


$read = new \React\Stream\Stream(fopen('php://stdin', 'r+'), $loop);
$write = new \React\Stream\Stream(fopen('php://stdout', 'w+'), $loop);
$run = true;
$read->on('data', function ($data, $read) use ($write) {
    global $run;
    if (trim($data) == 'quit') {
        $write->close();
        $read->close();
        $run = false;
    }
});

function manual_bot($loop) {
    global $run;
    return function () use ($loop) {
        global $run;
        // tge cide
//s//leep(3//as);
if ($run == false){
echo "exit";
    }else{
        $loop->futureTick(manual_bot($loop));
    }
    };
}
$loop->futureTick(manual_bot($loop));
$loop->run();

`

**Comment by clue** [comment]
The event loop always keeps running as long as there's something to do and you do not explicitly call `stop()`. This means that as long as any listener is attach to the loop, it will keep running. To stop the loop, simply remove the last listener and it will halt automatically. See also the first examples from our `examples/` folder which showcase this.

I hope this helps :+1:
