### ISSUE TITLE
Priority issues with multiple timers

### ISSUE THREAD

**Issue by davidwdan** [reactphp/event-loop#14]
If you run the following code

``` PHP
$loop = \React\EventLoop\Factory::create();
     for ($counter = 1; $counter <= 5; $counter++) {

         echo "Counter before loop {$counter}\n";
         $loop->addTimer(0.001, function () use ($counter) {
             echo "Counter in loop {$counter}\n";
         });
     }

$loop->run();
```

You get this output

``` shell
Counter before loop 1
Counter before loop 2
Counter before loop 3
Counter before loop 4
Counter before loop 5
Counter in loop 1
Counter in loop 5
Counter in loop 4
Counter in loop 3
Counter in loop 2

```

The counter within the loop should be in the same order as the counter before the loop.

It looks like the issue is with line 33 in Timers.php.  It adds the interval to `$this->getTime()`, which doesn't change.

A simple fix is to replace getTime() with updateTime(), which works as expected, but I'm not sure it that causes issues anywhere else.

``` PHP
$scheduledAt = $interval + $this->updateTime();
```

Let me know if you don't think it'll cause any other issues and I'll submit a PR.

**Comment by compunect** [comment]
The event scheduler definitely needs a priority setting, so a timer or any event can be pushed up in priority to ensure it's handled.
When using React with a websocket and the data input gets too high I've seen timers that should execute every second to be delayed by minutes.

**Comment by WyriHaximus** [comment]
hey @compunect, using an event loop like `ext-uv` could help with that. However is also depends on the number of connected clients, how much data they are sending around, what else you are doing inside the event loop.

**Comment by compunect** [comment]
> hey @compunect, using an event loop like `ext-uv` could help with that. However is also depends on the number of connected clients, how much data they are sending around, what else you are doing inside the event loop.

Hi,
Thanks for the recommendation, I've not known libuv before so I'm a bit blank on that.
Though it looks like a quite capable framework.

I could not find any type of documentation on it for ReactPHP, no samples either.
In general it looks like there are 4 or 5 loop implementations and only the php native one is documented.

In my example I have a slight database bottleneck, it's very hard to debug with reactPHP.
It would be great to have some debug functionality to check if the loop is in good health, if it has events queued, if the queue is growing.

I'll dig a bit into the source code for ExtUvLoop.

About my case:
I have a websocket connection with 300-400 streams, quite busy. It regularly disconnects abnormally, that's how I started to dig into this. Then I noticed that important timers are not being processed (at all), that's how I found this thread.
I tried switching to libuv and noticed a significant stability improvement.
With the native loop I had a response time of 6 minutes from the websocket (the event queue likely filled badly).
With the uv loop I get the response after 4 seconds, which is still 3.95 seconds slower than I would like but that's a significant upgrade.

**Comment by clue** [comment]
@compunect Thanks for reporting, this shouldn't have happened!

However, I don't think what you're describing is related to this original ticket. The original ticket deals with scheduling multiple timers to fire at the exact same time. We've clarified this with #157.

In your case, it looks like you might have some blocking code in your application that blocks the entire event loop. This is something that should be avoided for precisely this reason. If you need help with sorting this out, perhaps you can file a separate ticket with some more details so more people can take a look at this?
