### ISSUE TITLE
[Question] How to prevent the amount of ram used from rising in the loop

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/event-loop#140]
Hi, I have a problem. I have a loop with a futuretick that connects to the database only once and begins to make requests and update data, the problem is that the percentage of ram on the server does not stop uploading. It goes on and on with each iteration of the loop.

What are the recommendations so that this loop can keep the server running so that this does not happen?
I have to clean the cache?
destroy objects?
or is there something else that makes this happen?

**Comment by clue** [comment]
Thank you for raising this interesting question!

As a general rule: ReactPHP strictly avoids keeping things in RAM and as such we're not aware of anything that keeps growing (memory leaks).

That being said, the memory usage of your particular application depends on your particular business logic. It sounds like you may be sending a database query on each loop tick and store the results in memory? Note that the loop is *really* quick and iterates thousands of times per second. If your application actually works like this, it's really easy to take up all available RAM until the process is killed by your operating system.

As an alternative, you may want to use timers with a slower interval or use some pooling logic to limit the number of concurrent database queries to a reasonable limit. The suggested limit, again, depends on your particular problem, but limiting this to a few hundreds or thousands is probably a good idea.

I hope this helps :+1:
