### ISSUE TITLE
Optionally inject EventBase into ExtEventLoop

### ISSUE THREAD

**Issue by cameronjacobson** [reactphp/event-loop#15]
I am working on a project that I think could be complementary to your project:
  https://github.com/cameronjacobson/Spas

*\* Look at examples/\* files for a quick glimpse into what I'm trying to do.

Not as a component of React, but by using react as an injectable component in my project.  Similar to how "Request" variables are injected into callbacks in Silex.  I would write a ControllerResolver that injected additional components.  The reason I'm writing this note is because my project assumes its own EventBase (using EventHttp) is already instantiated.  And since using React as an injectable component would be optional, it wouldn't necessarily make sense to do all the React initialization up front.  So if a user could inject a React event-loop (using the EventBase already instantiated) the user could use React inside the Silex controller seamlessly.

When reviewing the event-loop project I noted the 'private' visibility for the EventBase.  I understand that my use-case may not be something you have thought of, but I think it's a valid one and I think would be pretty powerful way to utilize React.

I see that another option is for me to just implement the LoopInterface in my own implementation of an EventLoop for your project, and perhaps you feel better going that route, but given the new use case it seems it could open alot of possibilities for your project if either visibility was increased / getters / setters, and / or perhaps EventBase was injectable into the event-loop itself.

**Comment by JostBaron** [comment]
I have the same problem - I have a project that uses its own EventBase, without using the react loop. However, one dependency is `cboden/ratchet`, and that project requires an react event loop.

I'd like to just add the react event loop to my own EventBase, and not create a timer event on my own EventBase, in which the `tick()`-method of the react loop is called.

**Comment by clue** [comment]
Thanks for reporting this! :+1: While I agree that this is certainly not React's main focus, I think it's reasonable to (optionally) inject the EventBase into the ExtEventLoop.

Does anybody feel like creating a PR for this? :+1:

**Comment by cameronjacobson** [comment]
@clue I'm certainly willing to if someone doesn't beat me to it.  I should have time this weekend.  Thanks.

**Comment by cameronjacobson** [comment]
@clue not sure how much time you'd want to spend discussing this, but I at least just wanted to clarify "scope" of what I'm going to do here before I send a pull request.

I can see a "fast path" where we are only concerned with making the change to the ExtEventLoop.  I did this so far locally.  I can also imagine concerns such as wanting to try and keep the interface for the __construct method and/or behaviors / capabilities similar across the different LoopInterface implementations.

Of the 4 LoopInterface implementations, it looks like it's relatively straightforward to add the change to 3 of them (ExtEventLoop, LibEventLoop, and LibEvLoop).  The 4th (StreamSelectLoop) I think would be possible, to optionally "decouple" the stream_select loop from ReactPHP, but I would need to put more thought into it.

**Comment by clue** [comment]
Ping @cameronjacobson, what is the status here? I'm unsure where we left off and whether there's still interest in this issue. Also, it's currently a bit unclear how much value this provides and whether it's worth the effort implementing and maintaining this.

**Comment by perpetualcrayon** [comment]
@clue I think it could be an extremely powerful capability.  In other words, the design currently assumes ReactPHP will be the "container" for all functionality.  This would allow ReactPHP to behave in a supporting role inside some other application.  My only concern was I wanted to circle back with you to discuss whether it would be a problem that there doesn't appear to be a straightforward way to implement this capability with the StreamSelectLoop.

I do see a potential path forward with StreamSelectLoop but it would require de-coupling that class to where it also had an "EventBase" that would be optionally injected like the other loop classes.

Before I submitted a pull request I wanted to know what you thought about both approaches (ie. ensuring all Loop classes had same semantics, or if it would be better to leave StreamSelectLoop out of the equation).  And I wanted to confirm whether there was any development on the horizon that could interfere with the additional optional argument on the constructor, which would mean that if we proceeded we probably should ensure consistency across all Loop classes.

**Comment by cameronjacobson** [comment]
Sorry, previously submitted this comment using the wrong account :)

@clue I think it could be an extremely powerful capability. In other words, the design currently assumes ReactPHP will be the "container" for all functionality. This would allow ReactPHP to behave in a supporting role inside some other application. My only concern was I wanted to circle back with you to discuss whether it would be a problem that there doesn't appear to be a straightforward way to implement this capability with the StreamSelectLoop.

I do see a potential path forward with StreamSelectLoop but it would require de-coupling that class to where it also had an "EventBase" that would be optionally injected like the other loop classes.

Before I submitted a pull request I wanted to know what you thought about both approaches (ie. ensuring all Loop classes had same semantics, or if it would be better to leave StreamSelectLoop out of the equation). And I wanted to confirm whether there was any development on the horizon that could interfere with the additional optional argument on the constructor, which would mean that if we proceeded we probably should ensure consistency across all Loop classes.

**Comment by CharlotteDunois** [comment]
@cameronjacobson I think a better way would be to add an additional method (a setter, plus maybe a getter), to set the `EventBase` (or equivalent) for those loop implementations, which have it (e.g. no `select()` system call implementation). This way, you would not interfere with the constructor definition, plus only those which support some sort of base, have it. The only downside of this would be, that the constructor will create one anyway, even if it's not needed, but I think that's a compromise.

**Comment by tux-rampage** [comment]
> @cameronjacobson I think a better way would be to add an additional method (a setter, plus maybe a getter), to set the `EventBase` (or equivalent) for those loop implementations, which have it (e.g. no `select()` system call implementation). This way, you would not interfere with the constructor definition, plus only those which support some sort of base, have it. The only downside of this would be, that the constructor will create one anyway, even if it's not needed, but I think that's a compromise.

This is not better, it's way worse:

- It violates encapsulation
- It messes with the internal state of the loop instance (i.e. registered listeners)

Constructor injection is the only acceptable solution here. This could be done BC compatible as optional Constructor parameter.

**Comment by clue** [comment]
> @clue I think it could be an extremely powerful capability. In other words, the design currently assumes ReactPHP will be the "container" for all functionality. This would allow ReactPHP to behave in a supporting role inside some other application. My only concern was I wanted to circle back with you to discuss whether it would be a problem that there doesn't appear to be a straightforward way to implement this capability with the StreamSelectLoop.

I agree that there is some potential (perhaps hypothetical) advantage in said applications. From real world experience in production applications I would highly recommend against trying to use multiple event loops or abstractions thereof in a single application. I would argue that this often leads to more problems down the road, so I would suggest either using a single loop implementation, adapters for specific implementations or breaking up a larger application into smaller parts.

> I do see a potential path forward with StreamSelectLoop but it would require de-coupling that class to where it also had an "EventBase" that would be optionally injected like the other loop classes.

This sounds *interesting*… and *hard*. See above, I don't currently see any major benefit over the current architecture, but that doesn't mean that there's no value in it. With the current state of this discussion, I'm not sure it's worth the effort, but if you feel like working on this, then I'm happy to take a look at it and help reviewing.

I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please report back with more details if this is still an issue for you and we can reopen this :+1:
