### ISSUE TITLE
Support another EventLoop backend

### ISSUE THREAD

**Issue by Gemorroj** [reactphp/event-loop#152]
https://pecl.php.net/package/ev
http://docs.php.net/ev
any plans/ideas about implement adapter for this librarty?

**Comment by WyriHaximus** [comment]
Yes it is in the works for `0.5`: https://github.com/reactphp/event-loop/pull/148 and there is also an event-loop in the works for ext-uv https://github.com/reactphp/event-loop/pull/112

**Comment by Gemorroj** [comment]
thanks!

**Comment by kelunik** [comment]
You can also use [`amphp/react-adapter`](https://github.com/amphp/react-adapter) + [`amphp/amp`](https://github.com/amphp/amp), which will give you an `ev` based implementation – if `ev` is installed – that is fully compatible with ReactPHP's `LoopInterface`.

```php
$driver = (new Amp\Loop\DriverFactory)->create();
$loop = new Amp\ReactAdapter\ReactAdapter($driver);

// $loop is now a ReactPHP compatible driver based on ext-ev
```

If you don't want the automatic driver selection based on the available extensions, you can also instantiate a driver on your own using `$driver = new Amp\Loop\EvDriver;`.
