### ISSUE TITLE
Needs additional lower priority queue than futureTick

### ISSUE THREAD

**Issue by stgnet** [reactphp/event-loop#155]
The futureTick() queue provides a convenient way of scheduling discrete tasks for later execution.  While handy, it has a significant limitation:  In the event that a large number of callable functions (individually relatively short running, but collectively take a significant number of seconds to complete) are placed in this queue, the result will be that execution of all PeriodicTimer events, in addition to IO operations, are blocked.  Where I have lower priority functions that need run at a future time, but still want my periodic functions to called in a timely fashion, futureTick() fails to meet this need.

I propose that an additional queue for lower priority callable functions be added, where it would be essentially the same as the futureTick class except that the tick() member would essentially read:

    public function tick()
    {
        if (!$this->queue->isEmpty()) {
            call_user_func(
                $this->queue->dequeue()
            );
        }
    }
 
This would result in one callable from the queue being executed per iteration of the run() loop, allowing the IO and Periodic functions to be called.  Obviously the eventloop run() function would also be modified to call this additional queue's tick member following the established pattern.

In the interim, I have a workaround consisting of putting a single futureTick function in the queue that calls the first entry from my own queue, and then repopulates itself into futureTick to check again on the next run() loop.  However, having this a built-in feature of ReactPHP would be highly desirable over this hack.

**Comment by kelunik** [comment]
What's relatively short? What do the callbacks do? Why are they scheduled as `futureTick`?

**Comment by stgnet** [comment]
In my usage, which is a monitoring daemon, the callbacks perform a variety of http requests and mysql commands, usually taking a fraction of a second, sometimes as much as 2-3 seconds tops.  My Periodic events are at 10s and 60s, and also perform mysql commands mostly, and are not highly time critical (if 10s becomes 20s sometimes there is no problem, but >60s is).  Under certain circumstances, a large number (100s possibly even) of callbacks are queued.  I initially started using futureTick() to do this since they should not be delayed (no timer is needed), and purposefully designed them to spread the workload into smaller steps that would not take but a few seconds at most, thinking this prevent blocking Periodic functions.  Although the futureTick()::tick() function is appropriately executing only the ones present at the start of the function (so as to avoid subsequently queued functions), the fact that I'm dumping so many tasks in to the queue at once still results in delayed Periodic and IO events.

As stated, a workaround is in place that has completely resolved the problems by using my own separate queue that allows only one of the callbacks to be run per eventloop::run() loop.  Thus I'm simply recommending a lower priority queue be considered for inclusion in the package so I can drop my ugly hack at some point.

**Comment by kelunik** [comment]
So you're using blocking functions, which is the actual problem? Have you tried using a non-blocking HTTP client like https://github.com/reactphp/http-client instead?

**Comment by stgnet** [comment]
I am using http-client so that my requests are non-blocking, and that is a large part of the success of my application.  I've also broken up the sequential processing nature of the original code into smaller chunks so that no one task will consume more than a few seconds of cpu time.  The actual problem is that the loop->run() is written like this:

    while ($this->running) {
            $this->futureTickQueue->tick();
            $this->timers->tick();
            ...
    }

And futureTickQueue->tick() will run all the callbacks in the queue before returning, which if I overload the queue with too many things to do, timers and IO halt until the queued items are completed.  There are situations where this would be the desired outcome -- but in my case I need to prioritize timers/io over the backlog of entries in the queue (which is why I'm recommending a second lower priority queue with modified tick() behavior).

As a demonstration of the problem:

    $loop = React\EventLoop\Factory::create();
    $loop->addPeriodicTimer(1, function(){ echo "!"; });
    $count = 10;
    while ($count--) $loop->futureTick(function(){ sleep(1); echo ".";});
    $loop->run();

This will output ..........!!!!!!!!!! where the preferred output would be .!.!.!.!.!.!.!.!.! with an alternate low priority queue in place of futureTick.

**Comment by stgnet** [comment]
That would not resolve my problem, although I appreciate the suggestion.  In my case, many "threads" are spawned to investigate and update data, only some of which then need to make an http request and update information.  The fundamental problem that I needed to solve was the ability to queue many tasks in a way that did not prevent periodic or io functions from also being executed.  As stated, I have a workaround, and have made my suggestion on how to improve ReactPHP in a way that I at least would find beneficial.

**Comment by clue** [comment]
@stgnet Thank you for raising this very interesting discussion, I can certainly see where you're coming from!

I agree that a "lower priority queue" would be a possible work around for your particular problem. However, I'm currently failing to see how this would apply to other use cases. As a rule of thumb, we explicitly discourage blocking, see also https://github.com/reactphp/react/wiki/FAQ#how-can-i-use-blocking-functions.

This means that I don't currently see how we could possibly incorporate this here without breaking any of the existing assumptions. This being said, I think that your local solution sounds perfectly fine for your particular use case, so I would suggest simply keeping what you currently refer to as a "hack".

I hope this helps :+1:

**Comment by stgnet** [comment]
I agree that my workaround is suitable for my case.  As it turns out, to solve another problem, I ended up incorporating a deferred/promise into the solution and broke it out into it's own class, which gave me the ability to know when all the queued processing in a particular group had completed.  I will consider polishing that and contributing it.

**Comment by clue** [comment]
Happy to hear you've found a more permanent solution to your problem! Looking forward to your contribution, so make sure you send a ping our way :+1:
