### ISSUE TITLE
Bump PHP dependency from 5.3.0 to 5.4.0

### ISSUE THREAD

**Issue by Donatello-za** [reactphp/event-loop#165]
I personally use PHP 7.2 but I noticed after forking the project that its PHP dependency is currently set to `"php": ">=5.3.0"` in [composer.json](https://github.com/reactphp/event-loop/blob/f3ab8edeb6416466a73b1217b3af475ce9e3b087/composer.json). However, throughout the [ExtEvLoop](https://github.com/reactphp/event-loop/blob/882597b2c966a2bf236628942e37495830766c88/src/ExtEvLoop.php) class, arrays are declared like this: `private $readStreams = [];` which is a PHP 5.4 feature and will break when running under PHP 5.3.

Since most of the other ReactPHP projects already sets PHP 5.4 as the lower limit we may as well move it up for this project too.

Would you like me to fix it in my fork and send you a PR?

**Comment by clue** [comment]
@Donatello-za Thank you for spotting and reporting!

Theoretically, I agree that we should apply a consistent version constraint and this class would indeed fail to parse as-is on legacy PHP 5.3. This is very likely because there was an overlap between #151 and #148. As per #151 the other classes do indeed work with legacy PHP 5.3, though we discourage using legacy PHP versions and explicitly recommend using the latest supported version of PHP 7+.

Practically, this doesn't really matter as `ext-ev` requires PHP 5.4+ and as such this class is not used on older versions.

I hope this helps :+1: I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by Donatello-za** [comment]
High level IDE's such as PHPStorm and some linters synchronizes with composer.json and shows the array declarations as very clear errors as it picks up the discrepancy between the required PHP version and the newer style array declarations. One can override this by telling the IDE not to synchronize with composer.json but this means you loose other benefits to having it enabled.

I personally don't mind whether the dependency is bumped to 5.4 or the array declarations are modified to be compatible with PHP 5.3 (e.g. `private $readStreams = array();`) but it would be pretty terrible if it is left as is, because not only is it inconsistent with the other React libraries, it does actually cause issues. Apart from that, it would take less than a minute to make either change.

**Comment by clue** [comment]
> […] or the array declarations are modified to be compatible with PHP 5.3 (e.g. private $readStreams = array();) but it would be pretty terrible if it is left as is, because not only is it inconsistent with the other React libraries, it does actually cause issues. Apart from that, it would take less than a minute to make either change.

I agree that it makes sense to get this addressed. Feel like filing this as a PR and I'm happy to get this in? :+1:

**Comment by Donatello-za** [comment]
> Feel like filing this as a PR and I'm happy to get this in? 

Absolutely, thanks for considering it. 

I have forked from `master` and created a new branch called [issue-165](https://github.com/Donatello-za/event-loop/tree/issue-165) on my fork. I can do the PR now but would just like to confirm whether it is ok to have forked from `master` and whether I should request that my branch be merged into your `master` branch? I'm not sure what your contribution rules are so just asking before making assumptions.

**Comment by clue** [comment]
LGTM :shipit: :+1: 

I realize that the tone of my initial response may have come across as condescending, sorry for that. Legacy support is a very political topic (#151, https://github.com/reactphp/react/issues/374 and plenty others) and something that easily triggers a lot of people – both of which I'm not particularly fond of spending my holidays on.

Your input and your PR is very much appreciated, thank you!

**Comment by Donatello-za** [comment]
Hi, just did a PR. I completely understand your situation, no need to apologize :)
