### ISSUE TITLE
Support for getting informations from the event loop

### ISSUE THREAD

**Issue by CharlotteDunois** [reactphp/event-loop#172]
I am working for a way of getting support for sockets (using `socket_select` (or extension specific means, if available (libev and libevent have no specific support for sockets, both being obsolete))) into the event-loop through some sort of extension. This would be for socket communication between threads (stream sockets don't work).

Getting it into the event-loop is rather easy using future ticks - but the problem is, that there's no way of getting information from the event loop - such as if the future tick has any outstanding ticks, whether there are timers (and when will the first one fire) and whether there are any stream.

So it's impossible to make a decision whether the call can be blocking or not. So there's always the overhead of just ticking around, doing polling, even if there's nothing else going on and we could block for as long as needed.

So what am I exactly looking for, is an extension of the `LoopInterface` to expose the following information:
 - Whether there are any timers, and if so when does the first one fire. Return type possibly `int|null`.
 - Whether there are any outstanding future tick callbacks (excluding the one currently running (which is already done that way)). Return type `bool`.
 - Whether there are any streams (doesn't matter if read or write). Return type `bool`.

I can make a PR for this, if desired. But this would be a breaking change, as it's a change to the interface.

**Comment by kelunik** [comment]
The goal behind this suggestion seems to be to basically run two event loops concurrently (React's event loop and your extension of it). This won't work fine, because at some point you need _one_ blocking call that waits for the next timer a stream to be read- / writable.

Why can't you use stream sockets?

**Comment by CharlotteDunois** [comment]
No, it's just react's event loop. The extension will integrate into react's event loop using future ticks. Stream sockets are not threadsafe. Pure sockets appear to seem (according to tests).

**Comment by kelunik** [comment]
Could you outline how the integration will work and when the extension will schedule future ticks (how it uses the then exposed information)?

**Comment by CharlotteDunois** [comment]
Something along this sketch

```php
function addFutureTick() {
    $this->loop->futureTick(function () {
        $hasFutureTicks = $this->loop->hasFutureTicks(); // bool
        $firstTimer = $this->loop->getFirstTimer(); // int (time until first timer fires) or null (if none)
        $hasStreams = $this->loop->hasStreams(); // bool

        if($hasFutureTicks || $hasStreams) {
            // There is other work, just poll
            $timeout = 0;
        } else {
            if($firstTimer === null) {
                // No other work pending (no other ticks, no streams, no timers)
                // Block for as long as needed, until socket activity
                $timeout = null;
            } else {
                // Block until first timer fires (no other work besides to timers)
                $timeout = $firstTimer;
            }
        }

        // Other assignments related to the select call

        // Do the socket_select call for loop implementations with no specific socket support
        socket_select($readSockets, $writeSockets, $exceptSockets, ($timeout === null ? null : 0), $timeout);

        // Process result from the call

        $this->addFutureTick();
    });
}
```

**Comment by kelunik** [comment]
Yeah, that's running two event loops concurrently, one being `stream_select` (or whatever is called by an extension) and `socket_select`. As soon as you have at least one stream (which will generally be the case), you're in a busy loop that polls `stream_select` and `socket_select` both always with a timeout of `0` leading to 100% CPU usage all the time.

**Comment by CharlotteDunois** [comment]
Well, you could see this as two event loops. The best solution would be to integrate this into the native react event loop. But I don't see much use case other than my outlined use. How the integration would be done would only be true for the stream select loop and the two (obsolete) libev and libevent loop. Event and UV both provide support for sockets.

**Comment by kelunik** [comment]
Integrating this wouldn't change much, as it'd still have to call both functions without knowing which one should block. It's probably best to just require the event or uv extension in your case, or synchronize any access to the streams if they're not thread safe.

**Comment by CharlotteDunois** [comment]
Synchronization doesn't change anything. Streams are at the core of PHP just not safe for threading. Synchronization is even a blocking call, then I could just stay with my current solution of a timer and a volatile "messages cache" and check it periodically. Sockets would just be a better solution, "get notified when they arrive".

But you're right. There's no way of knowing which one should block when you have sockets and streams in your bucket, when you use the stream select loop.

**Comment by CharlotteDunois** [comment]
Both ext-event and ext-uv loop implementations (#112) support passing a socket instead of a stream to the `add*Stream` methods. Therefore I can make use of them when available, and fallback to my current solution. Since thanks to the reminder of @kelunik it actually does not make sense to implement `socket_select` at all, so I'll close this.

Thanks for the time!
