### ISSUE TITLE
Start non-blocking timer

### ISSUE THREAD

**Issue by StasToken** [reactphp/event-loop#173]
Writing php cls application.
You must call a specific code every n seconds.
The problem is that the called code is quite resource-intensive. I decided to use ReactPHP, which is kind of designed to solve this problem.
```
$loop = React\EventLoop\Factory::create();

$i = 0;
$loop->addPeriodicTimer(1, function() use (&$i) {
    res();
    echo ++$i, PHP_EOL;
});

$loop->run();

function res(){
    sleep(30);
} 
```
The problem is that when you call the **res()** function, the timer stops and waits until this function is not working, respectively, the timer is shifted to + the time of the function.

How to run a function on a timer synchronously to avoid lock timer at the time of its execution?

**Comment by CharlotteDunois** [comment]
What you want is **multithreading**. ReactPHP can not magically make blocking functions non-blocking. It's still singlethreaded - functions block the thread. You need to start a new thread or process and execute the function there.

**Comment by clue** [comment]
@StasToken Welcome to ReactPHP :-)

If you're looking for a "non-blocking timer", you can simple use the `addTimer()` method:

```
$loop->addTimer(30, function () {
    echo '30 seconds passed';
});
```

However, your question seems to be more geared towards using blocking functions within ReactPHP? The sort answer is: This is not supported by ReactPHP. The longer answer is that there are many non-blocking alternatives for ReactPHP you may either rewrite this using ReactPHP's primitives or you may spawn a new process and use inter-process communication, see also https://github.com/reactphp/react/wiki/FAQ#how-can-i-use-blocking-functions and https://github.com/reactphp/react/wiki/Users.
