### ISSUE TITLE
There is a Chinese Edition of the ReactPHP-EventLoop document ！！！

### ISSUE THREAD

**Issue by Lvsi-China** [reactphp/event-loop#178]
I translated the Chinese Edition of the ReactPHP-EventLoop document .

https://www.yuque.com/lvsi/reactphp-event-loop

**Comment by WyriHaximus** [comment]
That's amazing, thank you for translating out documentation to Chinese 👍 1

**Comment by clue** [comment]
I agree, thank you for providing this translated version and linking it here, I'm sure this is something a lot of people will appreciate! :clap:

**Comment by clue** [comment]
It's my understanding people searching for a Chinese translation will be able to find this ticket with your link irrespective of its status and I currently don't see anything that needs to be done here, so I believe this ticket can be closed.

@Lvsi-China Again thank you for providing this translation and linking it here!
