### ISSUE TITLE
StreamSelectLoop: Int overflow if the timer interval is big on 32-bit systems

### ISSUE THREAD

**Issue by tak3r** [reactphp/event-loop#19]
if $this->getNextEventTimeInMicroSeconds() in StreamSelectLoop.php returns a float value greater than max int value, it will give you this error 

stream_select(): The microseconds parameter must be greater than 0

This will happen if the next event interval is greater than 2148. Or, in other words you can't have a periodic timer with interval greater than 2148 seconds.

Workarounds: have a dummy periodic timer with interval less than 2148 seconds.

**Comment by alexmnv** [comment]
It is worth noting that the limit of 2148 seconds is only applied for 32-bit systems. On 64-bit systems it is big enough to not worry about it.
