### ISSUE TITLE
Default event loop

### ISSUE THREAD

**Issue by josephmiller2000** [reactphp/event-loop#190]
Well in default it uses "StreamSelectLoop" right?

I have a placed the code : $loop = React\EventLoop\Factory::create();

The loop instance is created at the beginning of the program. A convenience factory React\EventLoop\Factory::create() is provided by this library which picks the best available loop implementation.

Just to understand this clearly, if we install multiple event loops in single server? which event lop is used?

ext-event ?

ext-ev?

ext-uv?

or again it choose the " StreamSelectLoop " as a default loop? do we have to manually select which event loop should react use?

**Comment by clue** [comment]
@josephmiller2000 Here's an excerpt from the README:

> This method always returns an instance implementing LoopInterface, the actual event loop implementation is an implementation detail.

In other words, it will pick whatever is available on your system. If you do not install any particular extensions, it will default to the `StreamSelectLoop` which will work out-of-the-box on all supported PHP versions.

If you care about its implementation (and I don't think you should have to), you can take a look at the `Factory` class: https://github.com/reactphp/event-loop/blob/master/src/Factory.php

I hope this helps :+1:
