### ISSUE TITLE
Resume the connection after exception

### ISSUE THREAD

**Issue by caucik** [reactphp/event-loop#193]
After the exception in thrown the socket connection can no longer be properly closed nor resumed. See [Close behavior](https://github.com/ratchetphp/Pawl/issues/88).

**Comment by clue** [comment]
@caucik Thanks for reporting, I understand where you're coming from. Throwing an exception from any listener is not allowed:

> The listener callback function MUST NOT throw an Exception. The return value of the listener callback function will be ignored and has no effect, so for performance reasons you're recommended to not return any excessive data structures.
>
> https://github.com/reactphp/event-loop#addreadstream

As an alternative, I would recommend either letting the uncaught exception crash your application like it appears to do right now or if you want to handle it, wrapping your event handler code in a try-catch-block like this:

```php
$loop->addPeriodicTimer(3.0, function () {
    try {
        apiThatMightThrow();
    } catch (Exception $e) {
        // exception is non-fatal here, we simply log and wait for next iteration
        logException($e);
    }
});
```

I hope this helps :+1:
