### ISSUE TITLE
ExtUvLoop silently allows timers which cause integer overflow

### ISSUE THREAD

**Issue by CharlotteDunois** [reactphp/event-loop#194]
ExtUvLoop allows timers with an time or interval value that cause the internal conversion to cause an integer overflow to `0`.

https://github.com/reactphp/event-loop/blob/a0ecac955c67b57c40fe4a1b88a7cca1b58c982d/src/ExtUvLoop.php#L128-L133

Using `\PHP_INT_MAX` silently causes an integer overflow to `0`, and results in an intermediate firing of the timer callback.

The loop implementation should instead throw an exception if the conversion could cause an integer overflow.

**Comment by clue** [comment]
@CharlotteDunois Thanks for spotting and reporting, this is interesting!

On 32 bit systems this means that the maximum time interval is ~25 days (2^31 milliseconds). On 64 bit systems this is ~300 million years (2^63 milliseconds), so this is unlikely to be an issue for most common use cases. 

Is this something anybody would want to file as a PR with a simple test case?

**Comment by PabloKowalczyk** [comment]
@clue could I work on this issue?

**Comment by WyriHaximus** [comment]
@PabloKowalczyk go for it, AFAIK neither @clue or me are working on this at the moment. (It is on my/our list but not at the top.)
