### ISSUE TITLE
`futureTick` prevents `addPeriodicTimer` from functioning?

### ISSUE THREAD

**Issue by fideloper** [reactphp/event-loop#198]
Hello!

I seem to run into an issue where using `futureTick()` prevents `addPeriodicTimer` from ever firing.

I'm not sure if it's just my understanding that's at issue here. I swear I got this to run something exactly once, but subsequent attempts never worked.

* PHP 7.3.7 on Mac, installed via Brew
* No extra event libraries installed

Here are my examples:

```php
<?php

require_once "vendor/autoload.php";

use React\EventLoop\Factory;

$loop = Factory::create();

$timer = $loop->addPeriodicTimer(0.1, function() {
    echo "timer 1 ran!\n";
});

$loop->futureTick(function() use($loop, $timer) {

    echo "running stuff on next tick\n";
    file_get_contents('https://google.com');
    file_get_contents('https://yahoo.com');
    file_get_contents('https://stackoverflow.com/questions/1975461/how-to-get-file-get-contents-to-work-with-https');
    echo "got some sites\n";

    $loop->cancelTimer($timer);
});

$loop->run();

echo "DONE\n";
```

Another variation, same issue:

```php
<?php

require_once "vendor/autoload.php";

use React\EventLoop\Factory;

$loop = Factory::create();

$loop->futureTick(function() use($loop) {

    $timer = $loop->addPeriodicTimer(0.1, function() {
        echo "timer 1 ran!\n";
    });

    echo "running stuff on next tick\n";
    file_get_contents('https://google.com');
    file_get_contents('https://yahoo.com');
    file_get_contents('https://stackoverflow.com/questions/1975461/how-to-get-file-get-contents-to-work-with-https');
    echo "got some sites\n";

    $loop->cancelTimer($timer);
});

$loop->run();

echo "DONE\n";
```

Output:

```
running stuff on next tick
got some sites
DONE
```

If I don't use `futureTick()`, the periodic timer `echo` calls are output. I'm not sure what I might be doing wrong there. Thanks!

**Comment by WyriHaximus** [comment]
The `file_get_contents` function you're using is blocking the event loop (and the timer). If you want to fetch contents over HTTP(S) I would suggest https://github.com/clue/reactphp-buzz which integrates with the event loop and won't block anything.

**Comment by WyriHaximus** [comment]
> Is there a short-hand or general thing to know about what types of function calls block the event loop?


In short?: Everything.
In a bit longer: everything that doesn't leave the CPU is generally fine, once you hit I/O you start blocking the loop in a significant enough fashion that it will cause issues.

**Comment by WyriHaximus** [comment]
Any time! Also see https://github.com/reactphp/react/wiki/Users for tools you can use to interact with services
