### ISSUE TITLE
Suggest values in composer.json

### ISSUE THREAD

**Issue by hannesvdvreken** [reactphp/event-loop#22]
in [`composer.json`](https://github.com/reactphp/event-loop/blob/334abbbce8e4a48ed8283010149c4bceededacd4/composer.json#L10-L12) the `suggest` attributes have version "constraints".

According to the composer [documentation](https://getcomposer.org/doc/04-schema.md#suggest):
"The format is like package links above, except that the values are free text and not version constraints."
Generally it's saying that it will not fail when a wrong version is install.

Proposed solutions:
1. Maybe it's more useful to add a useful description so people know which extension is best to install. The version constraints can still be included in that description.
2. Maybe it's useful to write separate "driver" packages with the extensions as requirements. And make use of the `provide` to implement a virtual packages, which is "`suggest`ed" or "`require`d" in this package.

The latter is of course the more demanding proposal.

**Comment by cboden** [comment]
GitHub has an interesting interpretation of "2."  ;)

I'd prefer suggestion 1 over 2. Would you be interested in crafting a PR for the composer file?

**Comment by hannesvdvreken** [comment]
The reason for the unexpected interpretation is that markdown lists must be preceded with an empty line.

I'd like to create a PR but I don't know the differences between them, or which choice is preferred or has better performance or stability. Perhaps, is there some documentation on this somewhere?

**Comment by hannesvdvreken** [comment]
Nevermind, they are just different pecl drivers for the same system back-ends, so they are equally preferred.

**Comment by cboden** [comment]
Mostly. libev and libevent do differ in their implementations (at level lower than the PHP extensions). libevent came first and libev sought to "fix the problems with libevent". I don't know enough at a low level of either of them to make an informed comment on which is better. I know Facebook/HHVM uses libevent.
