### ISSUE TITLE
Loop signals in PHP8

### ISSUE THREAD

**Issue by mmoreram** [reactphp/event-loop#222]
Is a bit weird what happens in PHP8 around the loop signals. Basically because I can't figure out why they are not dispatched properly (for example, when Ctrl+C).

Did you find something similar while playing with PHP8?

**Comment by clue** [comment]
@mmoreram We're not aware of any issues at the moment, what's the problem you're seeing exactly?

Can you provide a gist with the expected and actual output?

**Comment by mmoreram** [comment]
It all started with a test under php8. Forcing the termination of the server was not actually working properly because of a sigint. With a reduction of the problem in a simple php file, I figured out that is actually working as expected. Weird.
I'm pretty sure that the pcntl extension in y CI has something to say here...

As soon as I have some extra info I will publish it here, and as soon as I have a response, I'll close this issue.
Thanks.

**Comment by mmoreram** [comment]
Ok, the change in php8 was exactly that one.

https://github.com/reactphp/event-loop/pull/217

I was not seeing this exception in my CI, and seems that in my local I was using a failing php8 installation.
After reinstalling amd hcanging the way errors are handled, seems that everything is working as expected.

Thanks for your time.

**Comment by clue** [comment]
@mmoreram Thanks for reporting back and happy to hear you've got this solved already :+1:
