### ISSUE TITLE
Infinite recursion bug with timers

### ISSUE THREAD

**Issue by apinstein** [reactphp/event-loop#223]
I've managed to reduce a bug I found in one of my programs to a simple test case:

```
<?php declare(strict_types=1);

require __DIR__ . '/src/bootstrap.php';

use Clue\React\Block;

function makeAPromise($loop):React\Promise\Promise {
  $deferred = new React\Promise\Deferred();

  $loop->futureTick(function () use ($deferred) {
      print "Future tick...\n";
      $deferred->resolve();
  });

  return $deferred->promise();
}

$loop = \React\EventLoop\Factory::create();
$loop->addTimer(0.1, function($timer) use ($loop) {
  // Without the statement below, this script recurses indefinitely
  $loop->cancelTimer($timer);

  print "In timer...\n";
  $promise = makeAPromise($loop);
  Block\await($promise, $loop, 2000);
});
$loop->run();
print "done";
```

The problem is caused by this block of code: https://github.com/reactphp/event-loop/blob/master/src/Timer/Timers.php#L95-L104
```
            $timer = $this->timers[$id];
            \call_user_func($timer->getCallback(), $timer);


            // re-schedule if this is a periodic timer and it has not been cancelled explicitly already
            if ($timer->isPeriodic() && isset($this->timers[$id])) {
                $this->schedule[$id] = $timer->getInterval() + $time;
                $this->sorted = false;
            } else {
                unset($this->timers[$id], $this->schedule[$id]);
            }
```

The `unset()` on the timer doesn't happen until after the timer callback completes, but if the timer callback ends up calling `$loop->run()`, the same timer will trigger AGAIN!

I am happy to submit a patch, but before I do, I wanted to check in w/you and see if this is a bug or if timer callbacks calling `$loop->run()` is somehow "bad behavior".

The reason I think that might be "bad behavior" (by Clue\React\Block) is that they are calling `$loop->run()` internally which also has the side-effect of breaking periodic timers... 

In any case, the patch, I think actually, is just to move the timer maintenance above the callback invocation:

```
            $timer = $this->timers[$id];

            // re-schedule if this is a periodic timer and it has not been cancelled explicitly already
            if ($timer->isPeriodic() && isset($this->timers[$id])) {
              $this->schedule[$id] = $timer->getInterval() + $time;
              $this->sorted = false;
            } else {
              unset($this->timers[$id], $this->schedule[$id]);
            }

            \call_user_func($timer->getCallback(), $timer);
```

This actually fixes what I think is a 2nd bug (or maybe a feature?) that periodic timers wouldn't re-schedule themselves until AFTER the callback completes, which, for callbacks that take some time, would cause the periodic triggers to drift apart from their "natural" schedule of always firing at t0 + n * timerDelay. But maybe that is a feature, and if so, just would need to move the non-periodic cleanup to prior to the callback.

Thoughts?

**Comment by WyriHaximus** [comment]
> The reason I think that might be "bad behavior" (by Clue\React\Block) is that they are calling `$loop->run()` internally which also has the side-effect of breaking periodic timers...

@clue's block is meant to be the starter of the loop. So, as you mentioned, in your script you're starting it twice, which, IMHO, make is "bad behavior" by "bad design" and would really advise you not to do so. However, I'm open to having a fix, that includes a test proving it has been fixed to make the event loop more resilient to accidental complexity issues like these.

Another option would be to throw an exception when trying to call run on an already running event loop, but that might be a BC break depending on how we documented that.

**Comment by apinstein** [comment]
Thanks for the response.

So I'm fine with either, but I've looked at the Block project more and it's not *clear* that it's just intended as the substitute for `$loop->run`. Coming from the js world of await/async, one would not expect such a limitation...

So, quite possibly Block is "behaving badly", but as for changing EventLoop to throw in this condition, it will likely cause lots of BC breaks for existing users.

Your call on which way to go...

Do you have advice on a more appropriate library to do `await` syntactical semantics that is more robust?

**Comment by clue** [comment]
@apinstein Thanks for reporting, I can see where you're coming from!

This is indeed a common misconception in clue/reactphp-block and not something that needs to be addressed in this event loop implementation.

This has been discussed in https://github.com/clue/reactphp-block/issues/49, https://github.com/clue/reactphp-block/issues/44, https://github.com/clue/reactphp-block/issues/20 and others. If you feel there's anyway I can help make this more obvious (better documentation?), please file a ticket for that project and I'm more than happy to discuss this further!

I believe this has been answered for this project, so I'm closing this for now. Please let us know if you feel there's anything that needs to be added :+1:

**Comment by WyriHaximus** [comment]
> Do you have advice on a more appropriate library to do `await` syntactical semantics that is more robust?

Well if you want to do `await` like syntactical semantics have a look at: https://github.com/recoilphp/recoil

**Comment by apinstein** [comment]
> @apinstein Thanks for reporting, I can see where you're coming from!
> 
> This is indeed a common misconception in clue/reactphp-block and not something that needs to be addressed in this event loop implementation.
> 
> This has been discussed in [clue/reactphp-block#49](https://github.com/clue/reactphp-block/issues/49), [clue/reactphp-block#44](https://github.com/clue/reactphp-block/issues/44), [clue/reactphp-block#20](https://github.com/clue/reactphp-block/issues/20) and others. If you feel there's anyway I can help make this more obvious (better documentation?), please file a ticket for that project and I'm more than happy to discuss this further!
> 
> I believe this has been answered for this project, so I'm closing this for now. Please let us know if you feel there's anything that needs to be added 👍

I read through all of those tickets and don't find that it really helps me understand what's going on.

While I do see firm stances "As a rule of thumb, mixing blocking and non-blocking code should be avoided", I actually have no idea what that means specifically. 

Architecturally, this is a not a rule of thumb in other languages that support async & await that I am aware of... Is this just a caveat of the implementation of ReactPHP? Or something more general? If it's more general I'd love to read a link explaining this if you know of a good explainer.

I appreciate that there's something here that's an unknown unknown for me, so I won't speculate yet on what the solution could/should be. But, with my "developer user of an async event loop" I would love to be able to block an async call in a synchronous block in certain situations. My guess is that this limitation is due to the event loop implementation under the hood, and maybe some extension-based async engines for php wouldn't have to have this limitation b/c they can use lower-level semantics to orchestrate it?

I've briefly looked through the code and it seems the trouble implementation-wise is that the `await X` semantics (in clue/block and [choval/async](https://github.com/choval/async/blob/af86eccf99895321bd55b93d75c5e8ecc35af0c8/src/Async.php#L216)) both invoke `run` on the loop. Which I think makes sense with your caveat as you cannot have a bunch of those fighting each other.

But, I am thinking about how we might get around that programmatically in pure php...

For instance maybe a block could internally use php coroutines to suspend itself synchronously, in coordination w/the core event loop.  I've played around a bit with this with no luck so far, just sharing my line of thinking.

**Comment by techno-express** [comment]
This might be of interest
https://medium.com/@interfacer/intro-to-async-concurrency-in-python-and-node-js-69315b1e3e36
then see the php version at
https://github.com/symplely/coroutine/blob/master/examples/async_scrape.php
it's reproducible with *recoilphp* just more code, files, and not look the
same.
