### ISSUE TITLE
Periodic timer jumping from one value to another directly.

### ISSUE THREAD

**Issue by CherukuriSiva** [reactphp/event-loop#225]
Thank You for open sourcing this great project. 

I am using event-loops in one of my WebSocket(RatchetPHP) related projects. 

I am running a periodic timer for every 0.1 seconds and the counter will start from 10. Every iteration I am decreasing 0.1 from the counter. So I should get values like 9.9, 9.8, 9.7 like this... till 0.0.

I have written the below code. It is working fine on my localhost but on the server machine, the values are jumping from 9.9 to 9.6 to 9.3 like this...

I have deployed my code Digital Ocean's hosting server. 
It is running on Ubuntu OS.
1 GB RAM. 25GB HardDisk.
I actually took the Basic plan. Can this be the reason? Because of limited RAM and availabe space, I am facing this issue.

KIndly help me.

```
        $seconds_counter = 10;
        $loop->addPeriodicTimer(0.1, function(TimerInterface $timer)  use(&$seconds_counter, $loop) {
            $seconds_counter = $seconds_counter-0.1;

            if($seconds_counter <= 0.0) {
                $loop->cancelTimer($timer);
            }
        });
```

**Comment by CherukuriSiva** [comment]
Sorry, it is something different. After debugging for around 1 hour I found the below points:

1. Found no issues with the Periodic timer and backend PHP code.
2. Front-end receiving incremental values correctly
3. But while displaying in the UI... somehow UI is skipping values.
4. This is happening only when I connect my front-end with 'server machine's backend.
5. When I connect with Localhost backend everything seems fine. UI is not skipping any values whatever the value received from the backend displaying as it is.

**Comment by clue** [comment]
@CherukuriSiva Thanks for reporting.

Your code snippet looks good to me and I don't see anything that would cause it to "skip values". This also shouldn't be affected by your platform and as far as ReactPHP is concerned, this machine doesn't have "limited RAM" :-)

I can only assume there's something wrong with your front-end code and/or how you're communicating these values with your front-end. If you can share more code, we might be able to help you, but then again this might be out of scope for this event-loop component?

Either way, I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
