### ISSUE TITLE
Experiencing issue with addPeriodicTimer seemingly just stopping randomly

### ISSUE THREAD

**Issue by mattmintun** [reactphp/event-loop#228]
Hey there! I'm using PAWL which implements reactphp event loop. I'm using it to connect to a websockets server. Once connected, I'm using `$loop->addPeriodicTimer()` to send a heartbeat back to the websockets server every 15s. This runs pretty solidly but at some point it just stops. No disconnect message from the websockets server. Absolutely no indication of it stopping. 

This last time, it got up to heart #769. I am logging the sending of the heartbeat and the response back from the server. I received a response back for the 769th heartbeat, but the periodicTimer never sent another heartbeat. 

I'm attaching an image of the logs:
![image](https://user-images.githubusercontent.com/36771702/117377681-b0cde180-ae88-11eb-9c68-240da98b6fb0.png)

I've attempted adding `$loop->addSignal(SIGINT, ....)` to capture a system disconnect (assuming that's what this would trigger from), but it never gets triggered. I have `$conn->on('close', ...)` that never gets triggered at this point either. 

It's as if the periodicTimer just stops. I checked the server resources at the same time and everything looks great there too. Only about 20% CPU usage, memory is low, nothing looks out of sorts. I'd just love to know how I can programmatically detect when this disconnect happens so I can reconnect. It's happening just about every day.

Thanks guys!
Matt

**Comment by clue** [comment]
@mattmintun Good question, this definitely shouldn't have happened!

We're not aware of any such issues in the event loop or Pawl, I've personally used both in a number of project that have been running for months straight with no issues whatsoever, so this is definitely known to work.

It's a bit hard to diagnose with the input you've provided, perhaps you can gist your code so we can reproduce this locally or see what could be wrong?

**Comment by mattmintun** [comment]
Hey @clue here you go! 
https://gist.github.com/mattmintun/6be6f27c1b4fd580c84b87d1ad08f71b

It's good to know that this _should_ work. Thank you for any direction you can offer up! I really appreciate it.

**Comment by WyriHaximus** [comment]
@mattmintun Remove these two lines https://gist.github.com/mattmintun/6be6f27c1b4fd580c84b87d1ad08f71b#file-pawl-eventloop-php-L69 and https://gist.github.com/mattmintun/6be6f27c1b4fd580c84b87d1ad08f71b#file-pawl-eventloop-php-L124

**Comment by mattmintun** [comment]
Thank you @WyriHaximus ! I've made those edits and am trying that now!

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
