### ISSUE TITLE
periodic timer with the interval of zero

### ISSUE THREAD

**Issue by my-random-username** [reactphp/event-loop#236]
Is this normal? periodic timer with zero value is executed only once . and never executes again !

        $timer = $loop->addPeriodicTimer(0,function ()use (&$timer){
           dump($timer); 
        });

the out put : 
```
React\EventLoop\Timer\Timer^ {#2409
  -interval: 1.0E-6
  -callback: Closure()^ {#2407
    class: "App\Console\Commands\Example"
    this: App\Console\Commands\Example {#2277 …}
    use: {
      $timer: React\EventLoop\Timer\Timer^ {#2409}
    }
    file: "./app/Console/Commands/Example.php"
    line: "91 to 93"
  }
  -periodic: true
}
```

**Comment by WyriHaximus** [comment]
To be honest, I'm not sure, adding a periodic timer with an interval of `0` is not an expected thing to do. Theoretically, it should trigger every loop iteration, creating a very busy loop, and completely utilizing a full CPU core. 

I'm assuming you want to have that function called a lot, and guessing 100 times a second is enough then using `0.01` should do the trick.

**Comment by my-random-username** [comment]
> To be honest, I'm not sure, adding a periodic timer with an interval of `0` is not an expected thing to do. Theoretically, it should trigger every loop iteration, creating a very busy loop, and completely utilizing a full CPU core.
> 
> I'm assuming you want to have that function called a lot, and guessing 100 times a second is enough then using `0.01` should do the trick.


in the path :  React\EventLoop\Timer\Timer
```
const MIN_INTERVAL = 0.000001;
```

```
if ($interval < self::MIN_INTERVAL) {
    $interval = self::MIN_INTERVAL;
}
```
There is a piece of logic in the timer class constructor that if the time is less than the minimum time, the minimum time is selected. But by selecting zero time, the timer no longer works periodically. And calls the callback only once

Even if I choose very small number instead of zero, the timer works periodically
```
$this->loop->addPeriodicTimer(0.0000000000000000000001, function () {
   echo "time is ticking...";   // this works periodically 
});
```
**This only happens when _ExtEvLoop_ is used and _StreamSelectLoop_ does not have this problem.**

**Comment by lucasnetau** [comment]
The ExtEvLoop implementation did not take into account the adjusted min bounded $interval stored in Timer. EvTimer was being initialised with a repeat value of 0, completing after the first invocation of the timer. A simple patch is proposed in PR #243
