### ISSUE TITLE
Rollback the deprecation of the Factory::create method

### ISSUE THREAD

**Issue by mmoreram** [reactphp/event-loop#237]
Even if the new versions work with a unique (and only unique) working loop, would be interesting to keep providing the opportunity to work with several Loop instances, for example for testing. Each TestCase should work as an isolated environment, and sharing the Loop as an static (and global) object, would destroy this circumstance.

The `Factory::create` method is important for testing, and by removing this method in the future, would break tons of testing files, as well as the opportunity of working with truly isolated test cases.

Please, consider rollback this deprecation.

**Comment by WyriHaximus** [comment]
It's deprecated and not removed. Any possible removal will happen in a major release, and we won't roll back the deprecation of it, this is the way we're moving towards too. Nothing stops you from instantiating event loops directly based on available extensions and test support for all of them. PHPUnit offers the ability to run each test in its own isolated process to achieve that same goal.

If tests rely on a fresh event loop it smells like there might be leftovers from previous tests in the event loop and that is something you'd really want to avoid and make sure you clean up the loop before finishing a test.

**Comment by mmoreram** [comment]
I would go for discussion. Basically because I have responses for all your comments.

But you know.
The issue is closed, like you don't really care about it.

Thanks.

**Comment by clue** [comment]
@mmoreram I agree with what @WyriHaximus said, but if you feel there's anything to add, feel free to comment on this ticket and we can always reconsider this :+1:
