### ISSUE TITLE
Question: error missing from register_shutdown_function when using implicit loop vs explicit loop.

### ISSUE THREAD

**Issue by nogoodcode** [reactphp/event-loop#239]
Hi, I'm running windows 10, using the test PHP Server that comes with PHP, and my version is PHP 7.4.9.

I'm starting the test server and then running the explicit loop until the 30s timeout is reached to see if the register_shutdown_function is called (Which it is.).
``` 
<pre>
<?php
require dirname(__FILE__)."/vendor/autoload.php";
register_shutdown_function(function () 
{
    $e = error_get_last();
    if (!empty($e)) 
    {
        print_r($e);
    }
    echo "shutdown";
});

use React\EventLoop\Loop;
$loop = Loop::get(); 
$timer = $loop->addPeriodicTimer(10, function () {
    echo 'Tick' . PHP_EOL;
});
$loop->run();
?>
</pre>
```

Here is the output:

```
Tick
Tick
Array
(
    [type] => 1
    [message] => Maximum execution time of 30 seconds exceeded
    [file] => G:\WebWork\reactphp\TestTimeout\vendor\react\event-loop\src\StreamSelectLoop.php
    [line] => 299
)
shutdown
```

Here, I am running the implicit loop but do not receive the error from the shutdown function.

```
<pre>
<?php
require dirname(__FILE__)."/vendor/autoload.php";
register_shutdown_function(function () 
{
    $e = error_get_last();
    if (!empty($e)) 
    {
        print_r($e);
    }
    
    echo "shutdown";
});

use React\EventLoop\Loop;
$timer = Loop::addPeriodicTimer(10, function () {
    echo 'Tick' . PHP_EOL;
});
?>
</pre>
```

Here is the output recevied.

```
shutdownTick Tick
```

Interestingly it looks like the Tick's are being buffered? and the error message is missing from the output. 

Just curious if this is expected behavior?
Thank you all!

**Comment by HLeithner** [comment]
The reason for this is that the autorun feature of the event loop is achieved by running the event loop in a shutdown function. 

https://github.com/reactphp/event-loop/blob/master/src/Loop.php#L47-L57

There are also some other problems with this solution mentioned by @kelunik at https://github.com/reactphp/event-loop/pull/232#pullrequestreview-696262824 -> https://3v4l.org/duM4S

You can work around this (if you need) by running the `Loop` manually `Loop::get()->run();` at the end of your code should be enough.

**Comment by nogoodcode** [comment]
Ahh Thank you @HLeithner! - That makes sense, thank you pointing to the code :)
