### ISSUE TITLE
[Help] Writing PHPUnit tests - Laravel

### ISSUE THREAD

**Issue by catabozan** [reactphp/event-loop#247]
My app listens for incoming emails for all of my users' email addresses.
I am using a `periodicTimer` to listen for incoming emails. When a new email is received, an event is dispatched.

I want to test that the event is dispatched when a new email is received.

The problem is that the event dispatches after the test is finished running, I checked using a `var_dump()` in the event class. And throws this error:
```
PHP Fatal error:  Uncaught ReflectionException: Class "auth" does not exist in 
/path/to/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
```

Also, even if I remove the test in question(the one that checks if the event is dispatched) and run the test suite, the PHP process keeps running even when the test suite has finished (the `periodicTimer` is called in the other tests, but no event is dispatched)

I think the `periodicTimer` keeps running even after the Laravel app shuts down (after the tests) and thus the `ReflectionException` when trying to dispatch the event.

I tried adding a `sleep()` in my test to give time to the event to get dispatched, but it doesn't dispatch at all. Then I thought that the sleep function was somehow blocking the `event loop` so I used a long-running `while()` but the event still got dispatched after the test ran, and the exception got thrown. (the while ran for 40 seconds). 

Has anyone encountered this issue before? Is there a way to test code running inside a `periodicTimer`, and also stop the event loop at the end of the test suite?

**Comment by WyriHaximus** [comment]
As long as the event loop runs, it will block everything else. How are you running the event loop in your tests?

**Comment by catabozan** [comment]
So basically, each time I create a user that has email credentials set up, another `periodic timer` is started.

When a user creates an account and submits its email credentials, an event is fired and a `periodic timer` is started for that user that listens for new emails from the IMAP server.

If I only run the test that checks for the event to be dispatched and call Loop::stop() at the end, the event never gets dispatched but the PHP process does not exit. My guess is that the `periodic timer` stops(so the event doesn't get dispatched) but the event loop is still running.

**Comment by SimonFrings** [comment]
@catabozan Thanks for bringing this up :+1: 

I noticed you asked the same question across multiple platforms. I don't have further information on this (what your code looks like etc.) so it's hard to go into detail. I took a look at the [reply on Reddit](https://www.reddit.com/r/laravel/comments/t8s7zz/testing_code_running_in_reactphp_event_loop/) and this is pretty much the same I would answer in this case.

> The only way to really test this is to call the class or function that receives the email and pass in a fake email body or contents.
>
>   The problem is that the event dispatches after the test is finished running,
>
>Mock the event loop or separate the code from it such that you do not need to touch it, or look up how to properly test the >contents of said event loop.
>
>If the test cannot be written, because of the complexity, the complexity needs to change such that the test can be written, my >first step would be to google: How to test code in a reactphp event loop, then I would examine my code and see what needs to >be refactored such that I can mock, test and get the results I expect.
