### ISSUE TITLE
Any way to "reset" the loop?

### ISSUE THREAD

**Issue by bpolaszek** [reactphp/event-loop#252]
Hey there! 👋 

I stumbled upon a kinda weird bug when using the loop in my CI, where some tests sometimes perform `Loop::stop()` when some others launch `Loop::run()` (though they don't run concurrently). This leads to fatal errors as raised [here](https://github.com/bpolaszek/freddie/runs/6285653775?check_suite_focus=true), although **they would not be raised when running tests one by one**. 🤨 

<img width="988" alt="Capture d’écran 2022-05-04 à 09 42 55" src="https://user-images.githubusercontent.com/5569077/166640554-4ef2077e-b46f-4909-a201-2992d72fee82.png">

I absolutely don't know how this is handled in the background as the fiber thing is kinda too low level to me, but it looks like the loop is sometimes left in some sort of stale state (which is not supposed to happen in production, as the loop  presumably runs once). 🧐 

[Spawning a new loop before each test](https://github.com/bpolaszek/freddie/pull/14/commits/4597b74165555bce23c81a833a96b60a5a44b3f2) is easy to do and [turns the tests to green](https://github.com/bpolaszek/freddie/runs/6285740778?check_suite_focus=true#step:5:206), except it relies on deprecated code. Do you know a better way to handle this? Otherwise would it be relevant to  add a `Loop::reset()` method? 💡 

As a side-feature-request, a `Loop::isRunning()` method would be a great help to avoid [this kind of tricks](https://github.com/bpolaszek/freddie/blob/feature/subscription-events/src/Hub/Hub.php#L75-L77) (yeah, this method can be invoked from an X-Framework app as well as from a regular PHP app, meaning the loop, in this case, just has to run to execute the promise and stop immediately afterwards) because we cannot know, from the outside, whether the loop is actually running or not.

Thanks! 🙏 
Ben

**Comment by SimonFrings** [comment]
Hey @bpolaszek, thanks for bringing this up :+1: 

I ran into something similar a while ago in https://github.com/reactphp/socket/pull/283. I would recommend to close everything at the end of your tests (Loop/connections etc.) to avoid leftovers.

I also noticed that you're using an older version of [reactphp/async](https://github.com/reactphp/async) (`futureTick` got removed in https://github.com/reactphp/async/pull/32) and [reactphp/eventloop](https://github.com/reactphp/eventloop) (you're using the `Facotry::create()` instead of `Loop::get()`, refs https://github.com/reactphp/event-loop/pull/226, https://github.com/reactphp/event-loop/pull/229 and https://github.com/reactphp/event-loop/pull/231). Maybe updating to the current versions will do the trick but I don't know for sure.

I hope this helps!

**Comment by bpolaszek** [comment]
Hi @SimonFrings,

Thank you for taking some time to look at this.

Regarding _react/async_, I just upgraded to the latest commit. Now I get a different error, but that's not the point.

How do you close the loop at the end of tests? By calling `Loop::close()`? 
So, [that's what I just did](https://github.com/bpolaszek/freddie/pull/14/commits/471490a98964f02ffa3bebffcc5b0f296f8e9b19), but a test is still failing [when the whole test suite is ran](https://github.com/bpolaszek/freddie/runs/6320625995?check_suite_focus=true#step:5:208). **It doesn't fail when ran alone.**

The only way I found to have the test suite running green is to uncomment [this line](https://github.com/bpolaszek/freddie/pull/14/commits/471490a98964f02ffa3bebffcc5b0f296f8e9b19#diff-8e1a60ab64729249b544e53c76aaced5c3bc744d410c48c6d11e2c901ffec1d1R16). And I'm using the deprecated `Factory::create()` just because `Loop::get()` doesn't work, as the latter returns an (already used) singleton instead of a fresh instance. 

So, as my problem is to rely on the deprecated `Factory::create()` method, how am I supposed to handle this?

**Comment by clue** [comment]
@bpolaszek I agree that this can be cumbersome sometimes, but I concur with everything @SimonFrings said: As a rule of thumb, you should never call `Loop::stop()` unless you're absolutely sure there's no alternative.

I understand it's tempting to call `Loop::stop()` in tests to interrupt the execution, but what it really means is that there are still listeners attached to the loop that will resume running the next time you call `Loop::run()`. As an alternative, I would highly recommend cleaning up any listeners as part of each test. Cleaning up any listeners allows the loop to stop automatically when it has nothing left to do (no timers and streams attached).

You can take a look at the referenced tickets and also https://github.com/reactphp/event-loop/issues/237 for some additional discussion about this. I'm happy to discuss if you feel there's anything else that needs to be done on our end here.

I hope this helps! :+1:

**Comment by bpolaszek** [comment]
I didn't remember participating in #237 so it looks like that same issue happened to me earlier and I ran into it again! 😅 

Well, then I'll first rely on the deprecated `Factory::create` until its sunset, as there's no such thing as a "listener collector" (which is, from my POV, the Loop instance's job) we could invoke to clear them all.

Cheers!
