### ISSUE TITLE
Have a look here

### ISSUE THREAD

**Issue by ClosetGeek-Git** [reactphp/event-loop#257]
Still a work in progress. https://github.com/ClosetMonkey/ReactPHPZMQ

**Comment by SimonFrings** [comment]
Hey @ClosetMonkey, looks like a cool project, thanks for sharing! 👍 

This ticket encourages me to start a discussion about adding "GitHub Discussions" to all ReactPHP repositories. There's currently only the possibility to open up a new issue, as you did, but I think this kind of ticket is more suited for a "GitHub Discussion" (under a category show your work).

I think we can close this ticket for now but we can transfer it into a Discussion (if everyone agrees to GitHub Discussions) for more visibility at a later point.

**Comment by clue** [comment]
@ClosetMonkey Interesting one! Make sure to add to our wiki (https://github.com/reactphp/reactphp/wiki/Users) and/or leave a link in https://github.com/friends-of-reactphp/zmq.

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:

**Comment by ClosetGeek-Git** [comment]
Working out some bugs first but then will do :thumbsup:
