### ISSUE TITLE
PHP8.4 - deprecations

### ISSUE THREAD

**Issue by flexiapp** [reactphp/event-loop#278]
Deprecated: GuzzleHttp\Ring\Core::proxy(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Core.php on line 334

Deprecated: GuzzleHttp\Ring\Core::proxy(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Core.php on line 334

Deprecated: GuzzleHttp\Ring\Core::proxy(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Core.php on line 334

Deprecated: GuzzleHttp\Ring\Future\CompletedFutureValue::__construct(): Implicitly marking parameter $e as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php on line 23

Deprecated: GuzzleHttp\Ring\Future\CompletedFutureValue::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php on line 60

Deprecated: GuzzleHttp\Ring\Future\CompletedFutureValue::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php on line 60

Deprecated: GuzzleHttp\Ring\Future\CompletedFutureValue::then(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php on line 60

Deprecated: React\Promise\PromiseInterface::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/PromiseInterface.php on line 40

Deprecated: React\Promise\PromiseInterface::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/PromiseInterface.php on line 40

Deprecated: React\Promise\PromiseInterface::then(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/PromiseInterface.php on line 40

Deprecated: GuzzleHttp\Ring\Future\BaseFutureTrait::__construct(): Implicitly marking parameter $wait as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/BaseFutureTrait.php on line 40

Deprecated: GuzzleHttp\Ring\Future\BaseFutureTrait::__construct(): Implicitly marking parameter $cancel as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/BaseFutureTrait.php on line 40

Deprecated: GuzzleHttp\Ring\Future\BaseFutureTrait::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/BaseFutureTrait.php on line 83

Deprecated: GuzzleHttp\Ring\Future\BaseFutureTrait::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/BaseFutureTrait.php on line 83

Deprecated: GuzzleHttp\Ring\Future\BaseFutureTrait::then(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/ezimuel/ringphp/src/Future/BaseFutureTrait.php on line 83

Deprecated: React\Promise\FulfilledPromise::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 21

Deprecated: React\Promise\FulfilledPromise::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 21

Deprecated: React\Promise\FulfilledPromise::then(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 21

Deprecated: React\Promise\FulfilledPromise::done(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 36

Deprecated: React\Promise\FulfilledPromise::done(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 36

Deprecated: React\Promise\FulfilledPromise::done(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/FulfilledPromise.php on line 36

Deprecated: React\Promise\ExtendedPromiseInterface::done(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/ExtendedPromiseInterface.php on line 22

Deprecated: React\Promise\ExtendedPromiseInterface::done(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/ExtendedPromiseInterface.php on line 22

Deprecated: React\Promise\ExtendedPromiseInterface::done(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/ExtendedPromiseInterface.php on line 22

Deprecated: React\Promise\RejectedPromise::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 21

Deprecated: React\Promise\RejectedPromise::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 21

Deprecated: React\Promise\RejectedPromise::then(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 21

Deprecated: React\Promise\RejectedPromise::done(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 36

Deprecated: React\Promise\RejectedPromise::done(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 36

Deprecated: React\Promise\RejectedPromise::done(): Implicitly marking parameter $onProgress as nullable is deprecated, the explicit nullable type must be used instead in /var/www/vendor/react/promise/src/RejectedPromise.php on line 36

**Comment by clue** [comment]
Please take the time to properly report tickets. None of these messages have anything to do with this component and most of these messages don't even have anything to do with ReactPHP. It looks like you're using an outdated Promise version, see also https://github.com/reactphp/promise/releases/tag/v3.2.0, https://github.com/reactphp/promise/pull/260 and https://github.com/orgs/reactphp/discussions/589.
