### ISSUE TITLE
HHVM Event

### ISSUE THREAD

**Issue by cboden** [reactphp/event-loop#3]
Add @rosmanov's [HHVM Event](https://bitbucket.org/osmanov/hhvm-event) extension to Travis HHVM tests.

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from our end (no demand at the moment and more important outstanding issues currently), but I suppose we would be really happy to accept PRs :+1: 

I'm closing this for now as it hasn't received any input in a while and we have no plans to change this ourselves anytime soon. Please come back if you feel this is still an issue and we can reopen this :+1:
