### ISSUE TITLE
Add timer within launched loop doesn't work

### ISSUE THREAD

**Issue by ProPheT777** [reactphp/event-loop#31]
Hey, 

I'm making face to a problem, i need to dynamcally attach timer. I'm on the context of websocket server (on top of ratchet) and i would use timer to emit message. 

So i have created a component to attach timer on specific connection. But the callback is just played once :( 

It's the expected behavior ? Am i on the wrong to achieve that ? 

Thanks

**Comment by WyriHaximus** [comment]
The loop has two timers. A one-off timer that's named `addTimer` for a single time call. And `addPeriodicTimer` for repeating calls. My guess if that you're using `addTimer` while you are expecting `addPeriodicTimer`.

**Comment by ProPheT777** [comment]
You are right. I don't why i'm digging with "timer". :tired_face: 

Thank you ;)

**Comment by WyriHaximus** [comment]
Cheers. Forgot to add this but the first argument passed into a timer is the timer itself. You can stop it like this: `$timer->cancel();` (You get the same `$timer` return when adding it to the loop.)
