### ISSUE TITLE
Make loop classes extendable

### ISSUE THREAD

**Issue by RogerWaters** [reactphp/event-loop#41]
Hallo,
I currently working on an multi-processing library (https://github.com/RogerWaters/react-thread-pool) compatible with react. My problem is that I require some additional functionality on the loop classes and everything is private here. Best way will be to extend the loops and add the functions (afterForkParent, afterForkChild).
Would you prefer that I create an pull request with all the functions and variables protected within the classes, or would you prefer that I add those functions directly to the classes? The only alternative will be to reflect those classes and this will result in poor performance and bad readable code. Maybe anyone have another solution?

Thanks for your help
RogerWaters

**Comment by clue** [comment]
Making certain internals `protected` or `public` has come up quite a few times already and so far we've always found better/cleaner solutions.

Can you elaborate on this a bit, i.e. give some background what these functions are supposed to do and why they're needed?

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
