### ISSUE TITLE
addPeriodicTimer() blocks the execution of my code

### ISSUE THREAD

**Issue by nesttle** [reactphp/event-loop#54]
Hi folks!

I have a code like this:

> ```
>       if ($message->content == 'startrare') {
>           $loop->run($timer);
>       } 
> ```

When if = true, loop runs and my code stops executing. Acts like a traditional php while/foreach...

Loop code looks like this:

> $loop = React\EventLoop\Factory::create();
> $i = 0;
> $timer = $loop->addPeriodicTimer(5, function() use (&$myvar0, $loop, &$myvar1, &$myvar2, &$myvar3) {
> echo 'OK';
> ...

I receive 'OK' each 5 seconds, but other code after (or before) loop not working until loop stops :/

**Comment by WyriHaximus** [comment]
Can you gist your full code? Also there can only be one loop running at once

**Comment by nesttle** [comment]
Yes, sir. Also I'm using DiscordPHP (https://github.com/teamreflex/DiscordPHP)

http://pastebin.com/5Gq0ujMu

**Comment by WyriHaximus** [comment]
So here is your problem. When calling [`Discord::run` that directly calls the event loop](https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Discord.php#L1223). So when you get a message from discord and try to run `$loop->run($timer);` you're already in a running loop, calling `Loop::run` again will block everything.

**Comment by nesttle** [comment]
Hi WyriHaximus :)

So, there is no workaround for this? 

PS: I just realized that I follow your examples to build my code https://blog.wyrihaximus.net/2015/01/reactphp-timers/ haha

**Comment by WyriHaximus** [comment]
> So, there is no workaround for this?

For what you're doing there code wise, no. But the real question is what are you trying to achieve? My guess is that that is the moment you want to start the timer you define instead of right at the start

> PS: I just realized that I follow your examples to build my code https://blog.wyrihaximus.net/2015/01/reactphp-timers/ haha. Congrats for your nice blog :)

Thanks :sunglasses: !

**Comment by nesttle** [comment]
Hello sir,

Well, we need to execute the $timer loop when explicit command/message is received in our chat log. Base code for the bot is this (DiscordPHP, using ReactPHP event-loop):
http://pastebin.com/jsNHXMcP

>             if ($message->content == 'startloop') {
>                 echo "Start my ReactPHP event-loop", PHP_EOL;
>                 $loop->run($timer);
>             }

Code of  **_$loop->run($timer);_** is here:
http://pastebin.com/A5pVNqMf


**_Issue_**: when loop $timer starts (startloop), bot don't listen any other commands, messages. Loop runs with no stop.
 I will need to think about other solution for this, but really don't know how to achieve this since DiscordPHP is based in ReactPHP event loops too :(

**Comment by nesttle** [comment]
I will execute my loop with discord->run(), since DiscordPHP supports one custom loop running with the main app. My problem now is how to pass a `$variable` from one loop to another:

> $myArray['mykey'] = 1;
---

> $mycustomloop = React\EventLoop\Factory::create();
> $i = 0;
> $mycustomloop->addPeriodicTimer(5, function() use (&$myArray, &$i) {
>     echo $i, PHP_EOL;
>     if (($i > 0)) {
>         echo "Hey, More than zero", PHP_EOL;
>     } else {
>         echo 'Hey, First loop, zero '.$i, PHP_EOL;
>     } 
>     if (($myArray['myKey'] == 1)) {
>         echo 'Variable found!', PHP_EOL;
>     }    
>     $i++;
> });

**Comment by dustingraham** [comment]
Whatever you're trying to do $loop->run() for, you probably want to use the existing Discord loop that's already running. So rather than creating your own loop, add timers and stuff to the discord loop.

**Comment by clue** [comment]
> Issue: […] Loop runs with no stop.

This is indeed expected behavior and in fact the whole point about having a loop in the first place. The main event loop keeps running forever (or until there's nothing to do anymore).

> My problem now is how to pass a $variable from one loop to another:

See above, there should only ever be a single loop in your application.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
