### ISSUE TITLE
Time callback

### ISSUE THREAD

**Issue by sm2017** [reactphp/event-loop#63]
How can I pass argument to a timer callback ?

**Comment by clue** [comment]
The `Timer` does indeed have a `setData()` method, but it's generally recommended to use closures like this instead:

```php
$greeting = 'hello';
$name = 'world';

$loop->addTimer(1.0, function() use ($greeting, $name) {
    echo $greeting . ' ' . $name . PHP_EOL;
});
```

I hope this helps :+1:
