### ISSUE TITLE
Prioritizing events in the loop

### ISSUE THREAD

**Issue by vaibhav-kaushal** [reactphp/event-loop#64]
I am just starting with react so my question might be dumb. Pardon me for that, but here it is: 

I have a Socket server with React. The use case of this server is to receive objects from its clients (which would mostly be my own web app backend) and dispatch them to external services via standard APIs - like sending email, sending SMS, sending messages to slack channel, push notifications, etc.

I do something like this: 
```php
require_once 'autoload.php';
	use \App\Experiment\SenderService;

	/** @var \React\EventLoop\StreamSelectLoop $loop */
	$loop = React\EventLoop\Factory::create();
	$server = new React\Socket\Server($loop);

	$connectionPool = new \SplObjectStorage();

	$server->on('connection', function ($conn) use ($connectionPool, $loop) {
		$strDataRead = 'xyz';
		/** @var \React\Socket\Connection $conn */
		$conn->on('data', function ($data) use ($connectionPool, $conn, &$strDataRead) {
			$connectionPool->attach($conn);

			$obj = unserialize($data);
			
			$strDataRead = serialize($data);
		});


		$conn->on('end', function () use ($connectionPool, $conn, &$strDataRead, $loop) {
			$connectionPool->detach($conn);

			$loop->futureTick(function () use ($strDataRead) {
				SenderService\Dispatcher::Dispatch($strDataRead);
			});
		});
	});

	echo "Socket server listening on port 4000.\n";
	echo "You can connect to it by running: telnet localhost 4000\n";
	$server->listen(4000);
	$loop->run();
```

The problem here is that when I send burst connections to the server using another script, the initial 30-40 requests get queued up real fast and then the server slows down and starts accepting requests at only about 1 request per second and that is very slow and defeats the purpose of the very service that I am trying to create. 

My understanding is that it stats ticking using the tick function: 

```php
public function tick()
    {
        $this->nextTickQueue->tick();

        $this->futureTickQueue->tick();

        $this->timers->tick();

        $this->waitForStreamActivity(0);
    }
```
And there, it waits for stream activity only **after** it has processed all the ticks. Since there are now about 30-40 requests queued up, it gets slow. (I might be wrong in my assumption; please tell me if I am). 

I want to prioritize the incoming connections to the server over the dispatcher so that the service is always ultra responsive in accepting new requests and goes on dispatching when it gets the time. How do I do that?

**Comment by clue** [comment]
Welcome to React :-)

The problem you're seeing likely doesn't come from improper prioritization but most likely from the fact that your SenderService\Dispatcher appears to be blocking the loop. The loop must never be blocked and may have to be rewritten to take advantage of the loop.

I hope this helps :+1:

**Comment by vaibhav-kaushal** [comment]
@clue Thanks for the diagnosis. You are right. So if that service is blocking the loop, how do I make sure it does not block the loop? The dispatcher does all the external communications stuff. So all the time taken for communicating with the third party servers starts blocking the loop. I cannot do anything about that. Also, I cannot run more than one loop; and ticking is synchronous.

If you could, give me a clue 😛 about how not to block the loop when calling the dispatcher?

**Comment by clue** [comment]
> The dispatcher does all the external communications stuff. So all the time taken for communicating with the third party servers starts blocking the loop.

You should probably look into the Stream and Socket component here :+1: Your communication has to be changed to be non-blocking in order to fully take advantage of the loop.
