### ISSUE TITLE
Use monotonic time when available

### ISSUE THREAD

**Issue by kelunik** [reactphp/event-loop#73]
Currently, PHP doesn't support and built-in way to access the system's monotonic time. That might change in PHP 7.2. I plan to implement a `hrtime()` function providing access to the high-resolution monotonic system time. If UV is available, but another loop is used, `uv_hrtime()` could be used in the meantime.

This issue exists to keep track of any improvements in PHP itself and to not forget implementing `hrtime()` in the future.

~~~https://externals.io/thread/592#email-14248~~~ updated: https://externals.io/message/97502

**Comment by clue** [comment]
I think this makes perfect sense and I'm sure we're going to add this once we have a reliable `hrtime()` implementation available :+1: 

(FWIW, this has also already been reported as part of #34)

**Comment by clue** [comment]
Ping @kelunik, what is the status here? :shipit:

**Comment by kelunik** [comment]
It didn't make it into PHP 7.2, maybe it'll be in PHP 7.3.

https://github.com/php/php-src/pull/2368

**Comment by clue** [comment]
I still think that using a monotonic time source make perfect sense. However, this is currently not available on PHP by default and it's unclear when the above PR lands in a future PHP version.

I'd like to make this actionable, so I've just added relevant documentation via #130 and marked this ticket as resolved for now.

I'm happy to look into this again once a monotonic time source is available in PHP by default :+1:
