### ISSUE TITLE
Possible of dealing with SignalEvent

### ISSUE THREAD

**Issue by foalford** [reactphp/event-loop#8]
Usually a script using event loop should be able to deal with signals. Instead of using pcntl functions, can we open up the support for SignalEvent? 

However as the loop is declared as private, there is no way of implement that by using either timer or tick queue. 

Any thought?

**Comment by clue** [comment]
See also #20 for a first starting point.

**Comment by jmalloc** [comment]
Hey all, I'll probably make an attempt at adding signal support to loop implementations as a matter of necessity. I was considering adding a `SignallingLoopInterface` with methods to register/unregister signal handlers. This interface would extend `LoopInterface`, as I'm not sure that all implementations can support signals in a useful way.  If it turns out that they can, we could roll the interfaces together. Thoughts @cboden / @clue / anyone?

**Comment by mikegioia** [comment]
@jmalloc Did you make any progress with that Interface? I'm in a hard place right now needing signal support for a React loop >_<

**Comment by cebe** [comment]
@mikegioia I am currently using https://github.com/mkraemer/react-pcntl in combination with this patch: #44. Would love to have some feedback in the PR.

**Comment by mikegioia** [comment]
@cebe I just tested out react-pcntl and applied your patch. It works :D :D However, we're still left with that unsuppressed warning from the `stream_select` failing. While I haven't written that test case, I'm pretty confident the performance penalty (if there even is one) is negligible for StreamSelectLoop users. I just wonder what the preferred method of dealing with this is. I'd hate to have to fork the repo to add my own @.

Has there been any movement on incorporating your patch?

**Comment by cebe** [comment]
I'd vote to add the `@` on `stream_select` but I'd also like to hear project maintainers opinion on this matter. @cboden @WyriHaximus what needs to be done to get #44 merged? Could you please take a look?

**Comment by jmalloc** [comment]
@mikegioia I havent had a chance to address it in any way I'd want to share, just some hacks to get us going at the moment :/

We use an error handler called [Asplode](http://github.com/eloquent/asplode), which produces  `ErrorExceptions` from old-style PHP errors. The solution for us was to catch an `ErrorException` from `stream_select` and call `pcntl_dispatch` if the error message describes a signal event. There's probably some overhead involved there, but we use signals in pretty standard ways (to trigger config reloads or to kill gracefully) so it hasn't been a problem.

I'm still keen to attempt a more general solution that doesn't use a timer, but I think it would require the okay to use `@` on `stream_select` as @cebe suggests, and simply call `pcntl_dispatch` if it's available when the return value is `false`. It's a bit more complex, but it looks like Icicle.io [does something similar](https://github.com/icicleio/icicle/blob/master/src/Loop/SelectLoop.php#L71).

**Comment by mikegioia** [comment]
Thanks @jmalloc. I ended up doing something similar with a custom error and exception handler. I'd be curious to see what you did with `pcntl_signal_dispatch` and why it was needed -- I didn't run into any issues with signal sending once I caught the warning, but I'm unfamiliar with what that function does :disappointed:

**Comment by jmalloc** [comment]
The handlers registered with `pcntl_signal` aren't actually invoked when the signal is received, they're only invoked when `pcntl_signal_dispatch` is called. I think it's somewhat common to register this function as a [tick handler](http://php.net/manual/en/function.register-tick-function.php), but I haven't tried that.

**Comment by cebe** [comment]
yes, you register it as tick handler in normal php or in a timer in the eventloop.

**Comment by cboden** [comment]
Supported now via #44
