### ISSUE TITLE
Allow multiple IO callbacks or throw

### ISSUE THREAD

**Issue by kelunik** [reactphp/event-loop#87]
Currently, multiple IO callbacks are ignored, only the first one will work. #86 fixes this to be consistent, but silently ignoring should be changed to either throw exceptions or call all handlers and not ignore them.

**Comment by clue** [comment]
I agree that adding multiple listeners to the same resource makes little sense and should not happen in a real world program :+1:

Throwing an exception in this case would be the obvious choice, does anybody feel like filing a PR? :shipit:
