### ISSUE TITLE
Why the new commits is not available in Packagist?

### ISSUE THREAD

**Issue by wafray** [reactphp/event-loop#98]
Great project.
And I have a question. I installed [reactphp/http-client](https://github.com/reactphp/http-client) with command ```composer install```, react/event-loop **(v0.4.2)** downloading and installed which has some bugs with #50 #42 #48 which cause my application error.  My question is when to publish the release?

**Comment by cboden** [comment]
It seems there's [1 remaining PR](https://github.com/reactphp/event-loop/pull/23) slated for v0.4.3

**Comment by WyriHaximus** [comment]
FYI [`v0.4.3`](https://github.com/reactphp/event-loop/releases/tag/v0.4.3) has just been released
